### ISSUE TITLE
感觉是一些依赖出问题了。

### ISSUE THREAD

**Issue by mem0rz** [zxkmm/gpt2-ml-fixed#4]
/content/drive/MyDrive/gptroot
Traceback (most recent call last):
  File "scripts/demo.py", line 7, in <module>
    import tensorflow.compat.v1 as tf
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 102, in <module>
    from tensorflow_core import *
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/descriptor.py", line 40, in <module>
    from google.protobuf.internal import api_implementation
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/api_implementation.py", line 104, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types

**Comment by zxkmm** [comment]
谢谢您的pr！

**Comment by mem0rz** [comment]
> 谢谢您的pr！

我不知道我哪里出问题了，你那边能成功运行吗？

**Comment by zxkmm** [comment]
> > 谢谢您的pr！
> 
> 我不知道我哪里出问题了，你那边能成功运行吗？

我一直能运行成功，这个提示是在第几个cell出现的？

**Comment by zxkmm** [comment]
> > 谢谢您的pr！
> 
> 我不知道我哪里出问题了，你那边能成功运行吗？

您能尝试一下新的ipynb吗？先到Gdrive把gptroot和子目录删了，然后重新用第一次准备的cell下载dependence和pre-trained文件？

**Comment by zxkmm** [comment]
您送了三个PR我还以为您那边是正常的

**Comment by mem0rz** [comment]
![火狐截图_2022-06-08T16-34-18 599Z](https://user-images.githubusercontent.com/14276116/172669877-d17df77c-2fb3-4ce6-913e-b02b2bbc1d42.png)
就最后一步

**Comment by mem0rz** [comment]
protobuf 
感觉是这个包的版本太高了。

**Comment by zxkmm** [comment]
> protobuf 感觉是这个包的版本太高了。

谢谢您，我明天尝试处理一下。

**Comment by mem0rz** [comment]
感觉要搞好了。我在尝试

**Comment by zxkmm** [comment]
> 感觉要搞好了。我在尝试

感谢。我刚刚用新账号跑了一遍，确实出现了问题，怀疑是谷歌又改了colab环境。

**Comment by mem0rz** [comment]
修好了

**Comment by zxkmm** [comment]
> 修好了

感谢！！！

**Comment by mem0rz** [comment]
close吧~

**Comment by zxkmm** [comment]
感谢！我将您的名字写在Credit里面，希望您喜欢！
